name: "Terraform Deploy"
on:
  workflow_dispatch:
    inputs:
      do_apply:
        type: boolean
        description: 'Run Apply?'
        required: true
        default: false
      region:
        type: choice
        description: 'Azure region for deployment'
        required: true
        default: 'eastus'
        options:
        - 'eastus'
        - 'westus'
permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash
 
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      #RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
      #STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
      #CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: latest
        
    - name: Terraform Init
      run: terraform init
      working-directory: ./
 
    - name: Terraform Plan
      run: terraform plan
      working-directory: ./
 
    - name: Terraform Apply
      #if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
      working-directory: ./
